# Generated by Django 4.1.3 on 2022-12-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('mobile_operator', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('tag', models.CharField(blank=True, default=None, max_length=255)),
                ('date_send_from', models.DateTimeField()),
                ('date_send_to', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
                'ordering': ('date_send_to',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_sent', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Отправлено'), (0, 'Не отправлено')], default=0, verbose_name='Статус отправки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('newsletter', models.ForeignKey(default='Рассылка удалена', on_delete=django.db.models.deletion.SET_DEFAULT, to='notification.newsletter')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('date_sent',),
            },
        ),
    ]
